#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
  procd_open_instance tailscaled
  procd_set_param command /usr/bin/tailscaled --state=/var/run/tailscaled.state
  procd_set_param respawn
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

stop_service() {
  /usr/bin/tailscale down   
}
